extends:
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order
ignore-files:
  - node_modules/**/*
plugins:
  - stylelint-order
rules:
  alpha-value-notation: percentage
  color-function-notation: legacy
  property-no-vendor-prefix:
  - true
  - ignoreProperties:
    - "/^mask-/"
  scss/double-slash-comment-whitespace-inside: null
